folders:
  - "~/Dropbox/Projekt/*"
  - "~/Dropbox/Programmering/Rust/*"
  - "~/.dotfiles"

commands:
  alt1:
    text: Terminal
    cmd: kitty --single-instance --directory ${path}
  alt2: 
    text: Neovim
    cmd: kitty --single-instance tmux new-session -c "${path}" "nvim ."
  alt3: 
    text: File Explorer
    cmd: pcmanfm ${path}
  

