swipe:
  3: # mainly browser navigation
    left:
      # go back
      command: 'xdotool key alt+Left'
    right:
      # go forward
      command: 'xdotool key alt+Right'
    up:
      # open new tab
      command: 'xdotool key ctrl+t'
    down:
      # close tab
      command: 'xdotool key ctrl+w'
  4:
    # make these cycle the awesome workspaces
    left:
      command: 'xdotool key alt+ctrl+Left'
    right:
      command: 'xdotool key alt+ctrl+Right' 

pinch:
  2:
    in:
      command: 'xdotool key ctrl+minus'
    out:
      command: 'xdotool key ctrl+plus'
 
threshold:
  swipe: 0.2
  pinch: 0.1

interval:
  swipe: 1
  pinch: 1
